name: grader-system-wth-hapi-prisma
on:
    push:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/grading-app
        steps:
            - name: Checkout repositoru
              uses: actions/checkout@v3

            - name: Setup  nodejs
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build source code
              run: npm run build

            - name: Run DB migrations
              run: npm run db:push

            - name: Run Unit tests
              run: npm run test
